In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("student-dataset.csv")
data.head(5)

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,3.7,2.6,3.4,1.0,4,4.0,5

In [4]:
gk = data.groupby('portfolio.rating')
gk.first()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,coverletter.rating,refletter.rating
portfolio.rating,,,,,,,,,,,,,,
1,72,Fikra al-Mina,India,Bombay,18.98,72.83,F,21,3.1,2.4,3.3,3.0,5.0,4
2,5,Rochelle Johnson,United States of America,Indianapolis,39.77,-86.16,F,21,3.4,3.1,3.7,5.0,4.0,4
3,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3.0,4
4,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4.0,4
5,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,4.0,5

In [5]:
result = gk['math.grade'].agg(['mean', 'var'])
result.reset_index()

   portfolio.rating      mean       var
0                 1  3.066667  0.493333
1                 2  3.295238  0.174476
2                 3  3.388679  0.247562
3                 4  3.417692  0.237592
4                 5  3.459000  0.208908

In [6]:
result = gk['sciences.grade'].agg(['mean', 'var'])
result.reset_index()

   portfolio.rating      mean       var
0                 1  3.500000  0.040000
1                 2  3.433333  0.218333
2                 3  3.415094  0.352460
3                 4  3.408462  0.255199
4                 5  3.514000  0.231317

In [7]:
result = gk['english.grade'].agg(['mean', 'var'])
result.reset_index()

   portfolio.rating      mean       var
0                 1  3.033333  0.493333
1                 2  3.371429  0.154143
2                 3  3.383019  0.319514
3                 4  3.360000  0.300403
4                 5  3.385000  0.292803

In [8]:
result = gk['refletter.rating'].agg(['mean', 'var'])
result.reset_index()

   portfolio.rating      mean       var
0                 1  4.333333  0.333333
1                 2  4.142857  0.328571
2                 3  4.113208  0.679245
3                 4  4.223077  0.655277
4                 5  4.190000  0.902929