In [75]:
import pandas as pd
import numpy as np
import plotly.express as px
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("train.csv")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [76]:
data.dtypes.to_frame()

                   0
PassengerId    int64
Survived       int64
Pclass         int64
Name          object
Sex           object
Age          float64
SibSp          int64
Parch          int64
Ticket        object
Fare         float64
Cabin         object
Embarked      object

In [77]:
data.isnull().sum().to_frame()

               0
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age          177
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin        687
Embarked       2

In [78]:
data.shape

(891, 12)

In [79]:
data = data.drop(['Embarked', 'Ticket'], axis=1)

data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,NaN

In [80]:
data.nunique().to_frame()

               0
PassengerId  891
Survived       2
Pclass         3
Name         891
Sex            2
Age           88
SibSp          7
Parch          7
Fare         248
Cabin        147

In [81]:
mode = data['Cabin'].mode()
mode

0        B96 B98
1    C23 C25 C27
2             G6
Name: Cabin, dtype: object

In [82]:
data = data.fillna(mode[0])
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,B96 B98
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,B96 B98
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,B96 B98

In [83]:
data['Sex'] = data['Sex'].replace({'female': 1, 'male': 0})
data.head(5)

C:\Users\Asus\AppData\Local\Temp\ipykernel_5568\3263801581.py:1: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,B96 B98
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,B96 B98
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,B96 B98

In [84]:
fig = px.histogram(data, x=data['Age'])
fig.update_layout(width=1000, height=300)
fig.show()

In [85]:
data['Age'] = pd.to_numeric(data['Age'], errors='coerce')

In [86]:
data.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,B96 B98
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,B96 B98
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,B96 B98
...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",0,NaN,0,0,8.0500,B96 B98
96,97,0,1,"Goldschmidt, Mr. George B",0,71.0,0,0,34.6542,A5
97,98,1,1,"Greenfield, Mr. William Bertram",0,23.0,0,1,63.3583,D10 D12
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",1,34.0,0,1,23.0000,B96 B98
99,100,0,2,"Kantor, Mr. Sinai",0,34.0,1,0,26.0000,B96 B98

In [87]:
median = data['Age'].median()
median

np.float64(28.0)

In [88]:
data['Age'] = data['Age'].fillna(median)
data.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,B96 B98
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,B96 B98
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,B96 B98
...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",0,28.0,0,0,8.0500,B96 B98
96,97,0,1,"Goldschmidt, Mr. George B",0,71.0,0,0,34.6542,A5
97,98,1,1,"Greenfield, Mr. William Bertram",0,23.0,0,1,63.3583,D10 D12
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",1,34.0,0,1,23.0000,B96 B98
99,100,0,2,"Kantor, Mr. Sinai",0,34.0,1,0,26.0000,B96 B98

In [89]:
data.isnull().sum().to_frame()

             0
PassengerId  0
Survived     0
Pclass       0
Name         0
Sex          0
Age          0
SibSp        0
Parch        0
Fare         0
Cabin        0

In [90]:
np.argwhere(data['Age'] < 1)

array([[ 78],
       [305],
       [469],
       [644],
       [755],
       [803],
       [831]])

In [91]:
data['Age'] = np.where(data['Age'] < 1, 0, data['Age'])
np.argwhere(data['Age'] == 0)

array([[ 78],
       [305],
       [469],
       [644],
       [755],
       [803],
       [831]])

In [92]:
data['Age'] = data['Age'].astype(int)

In [93]:
for col in data:
    fig = px.histogram(data, x=data[col])
    fig.update_layout(width=1000, height=300)
    fig.show()

In [94]:
def find_outliers_IQR(df_col):

   q1=df_col.quantile(0.25)

   q3=df_col.quantile(0.75)

   IQR=q3-q1

   outliers = df_col[((df_col<(q1-1.5*IQR)) | (df_col>(q3+1.5*IQR)))]

   return outliers.index



for col in data:
     if (data[col].dtype==int): 
        outliers = find_outliers_IQR(data[col])
        print(outliers)
        data.drop(index=outliers, inplace=True)

data

Index([], dtype='int64')
Index([], dtype='int64')
Index([], dtype='int64')
Index([], dtype='int64')
Index([  7,  11,  15,  16,  33,  54,  78,  94,  96, 116, 119, 152, 164, 170,
       172, 174, 183, 195, 205, 232, 252, 268, 275, 280, 297, 305, 326, 340,
       366, 381, 386, 438, 456, 467, 469, 479, 483, 487, 492, 493, 530, 545,
       555, 570, 587, 625, 626, 630, 642, 644, 647, 659, 672, 684, 694, 745,
       755, 772, 788, 803, 824, 827, 829, 831, 851, 879],
      dtype='int64')
Index([ 24,  27,  50,  59,  63,  68,  71,  85,  88, 159, 171, 176, 180, 182,
       201, 229, 233, 261, 266, 278, 324, 341, 374, 409, 480, 485, 541, 542,
       634, 683, 686, 726, 787, 792, 813, 819, 846, 850, 863],
      dtype='int64')
Index([  8,  10,  13,  25,  43,  58,  65,  86,  93,  97,
       ...
       852, 853, 855, 856, 858, 869, 871, 880, 885, 888],
      dtype='int64', length=144)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",0,22,1,0,7.2500,B96 B98
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38,1,0,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",1,26,0,0,7.9250,B96 B98
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35,1,0,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",0,35,0,0,8.0500,B96 B98
...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",0,25,0,0,7.0500,B96 B98
886,887,0,2,"Montvila, Rev. Juozas",0,27,0,0,13.0000,B96 B98
887,888,1,1,"Graham, Miss. Margaret Edith",1,19,0,0,30.0000,B42
889,890,1,1,"Behr, Mr. Karl Howell",0,26,0,0,30.0000,C148
890,891,0,3,"Dooley, Mr. Patrick",0,32,0,0,7.7500,B96 B98

In [95]:
heatmap_df = data.drop(['Name', 'Cabin'], axis=1)
heatmap_df.corr()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.049061,-0.027508,-0.106703,0.050350,-0.101478,NaN,0.010934
Survived,-0.049061,1.000000,-0.347756,0.584813,0.045147,0.118129,NaN,0.295226
Pclass,-0.027508,-0.347756,1.000000,-0.175708,-0.343656,-0.172640,NaN,-0.553293
Sex,-0.106703,0.584813,-0.175708,1.000000,-0.049058,0.165787,NaN,0.208694
Age,0.050350,0.045147,-0.343656,-0.049058,1.000000,0.077325,NaN,0.143766
SibSp,-0.101478,0.118129,-0.172640,0.165787,0.077325,1.000000,NaN,0.192606
Parch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fare,0.010934,0.295226,-0.553293,0.208694,0.143766,0.192606,NaN,1.000000

In [96]:
fig = px.imshow(heatmap_df.corr())
fig.show()

In [97]:
fig = px.scatter(
    data,
    x="Age",
    y="Survived",
    color="Pclass",
    hover_data='Age' 
)
fig.show()

In [98]:
for col in data:
    if (data[col].dtype==int): 
        print(f"mean of {col}:\n", data[col].mean())
        print(f"median of {col}:\n", data[col].median()) 
        print(f"mode of {col}:\n", data[col].mode())

mean of PassengerId:
 447.5934579439252
median of PassengerId:
 451.0
mode of PassengerId:
 0        1
1        2
2        3
3        4
4        5
      ...
637    885
638    887
639    888
640    890
641    891
Name: PassengerId, Length: 642, dtype: int64
mean of Survived:
 0.3442367601246106
median of Survived:
 0.0
mode of Survived:
 0    0
Name: Survived, dtype: int64
mean of Pclass:
 2.358255451713396
median of Pclass:
 3.0
mode of Pclass:
 0    3
Name: Pclass, dtype: int64
mean of Sex:
 0.2866043613707165
median of Sex:
 0.0
mode of Sex:
 0    0
Name: Sex, dtype: int64
mean of Age:
 29.560747663551403
median of Age:
 28.0
mode of Age:
 0    28
Name: Age, dtype: int64
mean of SibSp:
 0.2383177570093458
median of SibSp:
 0.0
mode of SibSp:
 0    0
Name: SibSp, dtype: int64
mean of Parch:
 0.0
median of Parch:
 0.0
mode of Parch:
 0    0
Name: Parch, dtype: int64

In [99]:
fig = px.box(data, x='Pclass', y='Age')
fig.show()